[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
dotenv = "0.15.0"
serde = "1.0.152"
serde_json = "1.0.93"
sqlx = {version = "0.6.2", features = ["postgres", "runtime-async-std-native-tls"]}
